from flask import Flask, request, jsonify, render_template

app = Flask(__name__)
raw_items = {
    "ENCHANTED_RAW_CHICKEN": "Enchanted Raw Chicken",
    "INK_SACK:3": "Cocoa Beans",
    "BROWN_MUSHROOM": "Brown Mushroom",
    "ENCHANTED_WATER_LILY": "Enchanted Lily Pad",
    "INK_SACK:4": "Lapis Lazuli",
    "TARANTULA_WEB": "Tarantula Web",
    "CARROT_ITEM": "Carrot",
    "ENCHANTED_POTATO": "Enchanted Potato",
    "LOG:1": "Spruce Log",
    "ENCHANTED_SLIME_BALL": "Enchanted Slimeball",
    "ENCHANTED_GOLDEN_CARROT": "Enchanted Golden Carrot",
    "LOG:3": "Jungle Log",
    "LOG:2": "Birch Log",
    "ENCHANTED_RABBIT_HIDE": "Enchanted Rabbit Hide",
    "ENCHANTED_GLOWSTONE_DUST": "Enchanted Glowstone Dust",
    "ENCHANTED_INK_SACK": "Enchanted Ink Sack",
    "ENCHANTED_CACTUS": "Enchanted Cactus",
    "ENCHANTED_SUGAR_CANE": "Enchanted Sugar Cane",
    "ENCHANTED_BIRCH_LOG": "Enchanted Birch Log",
    "ENCHANTED_GUNPOWDER": "Enchanted Gunpowder",
    "ENCHANTED_MELON": "Enchanted Melon",
    "ENCHANTED_COOKED_SALMON": "Enchanted Cooked Salmon",
    "ENCHANTED_SUGAR": "Enchanted Sugar",
    "LOG": "Oak Log",
    "CACTUS": "Cactus",
    "ENCHANTED_BLAZE_ROD": "Enchanted Blaze Rod",
    "GHAST_TEAR": "Ghast Tear",
    "ENCHANTED_CAKE": "Enchanted Cake",
    "PUMPKIN": "Pumpkin",
    "ENCHANTED_ENDER_PEARL": "Enchanted Ender Pearl",
    "PURPLE_CANDY": "Purple Candy",
    "WHEAT": "Wheat",
    "ENCHANTED_FERMENTED_SPIDER_EYE": "Enchanted Fermented Spider Eye",
    "ENCHANTED_GOLD_BLOCK": "Enchanted Gold Block",
    "ENCHANTED_RAW_SALMON": "Enchanted Raw Salmon",
    "ENCHANTED_JUNGLE_LOG": "Enchanted Jungle Log",
    "ENCHANTED_FLINT": "Enchanted Flint",
    "ENCHANTED_GLISTERING_MELON": "Enchanted Glistering Melon",
    "IRON_INGOT": "Iron Ingot",
    "PRISMARINE_SHARD": "Prismarine Shard",
    "ENCHANTED_EMERALD": "Enchanted Emerald",
    "ENCHANTED_SPIDER_EYE": "Enchanted Spider Eye",
    "ENCHANTED_EMERALD_BLOCK": "Enchanted Emerald Block",
    "RED_MUSHROOM": "Red Mushroom",
    "MUTTON": "Mutton",
    "ENCHANTED_MELON_BLOCK": "Enchanted Melon Block",
    "ENCHANTED_CLAY_BALL": "Enchanted Clay Ball",
    "DIAMOND": "Diamond",
    "COBBLESTONE": "Cobblestone",
    "SPIDER_EYE": "Spider Eye",
    "RAW_FISH": "Raw Fish",
    "ENCHANTED_PUFFERFISH": "Enchanted Pufferfish",
    "GLOWSTONE_DUST": "Glowstone Dust",
    "GOLD_INGOT": "Gold Ingot",
    "REVENANT_VISCERA": "Revenant Viscera",
    "TARANTULA_SILK": "Tarantula Silk",
    "POTATO_ITEM": "Potato",
    "ENCHANTED_MUTTON": "Enchanted Mutton",
    "ENCHANTED_HUGE_MUSHROOM_1": "Enchanted Brown Mushroom Block",
    "SUPER_COMPACTOR_3000": "Super Compactor 3000",
    "ENCHANTED_IRON": "Enchanted Iron",
    "SUPER_EGG": "Super Egg",
    "STOCK_OF_STONKS": "Stock Of Stonks",
    "ENCHANTED_COBBLESTONE": "Enchanted Cobblestone",
    "ENCHANTED_BONE": "Enchanted Bone",
    "ENCHANTED_PAPER": "Enchanted Paper",
    "ENCHANTED_HUGE_MUSHROOM_2": "Enchanted Red Mushroom Block",
    "PORK": "Pork",
    "ENCHANTED_DIAMOND_BLOCK": "Enchanted Diamond Block",
    "EMERALD": "Emerald",
    "ENCHANTED_RABBIT_FOOT": "Enchanted Rabbit Foot",
    "PRISMARINE_CRYSTALS": "Prismarine Crystals",
    "HOT_POTATO_BOOK": "Hot Potato Book",
    "ENCHANTED_ICE": "Enchanted Ice",
    "ICE": "Ice",
    "CLAY_BALL": "Clay Ball",
    "HUGE_MUSHROOM_1": "Brown Mushroom Block",
    "HUGE_MUSHROOM_2": "Red Mushroom Block",
    "LOG_2:1": "Dark Oak Log",
    "GREEN_GIFT": "Green Gift",
    "ENCHANTED_SNOW_BLOCK": "Enchanted Snow Block",
    "GOLDEN_TOOTH": "Golden Tooth",
    "STRING": "String",
    "PACKED_ICE": "Packed Ice",
    "WATER_LILY": "Lily Pad",
    "RABBIT_FOOT": "Rabbit Foot",
    "LOG_2": "Acacia Log",
    "REDSTONE": "Redstone",
    "ENCHANTED_OBSIDIAN": "Enchanted Obsidian",
    "ENCHANTED_COAL": "Enchanted Coal",
    "COAL": "Coal",
    "ENCHANTED_QUARTZ": "Enchanted Quartz",
    "ENDER_PEARL": "Ender Pearl",
    "ENCHANTED_COAL_BLOCK": "Enchanted Coal Block",
    "ENCHANTED_CACTUS_GREEN": "Enchanted Cactus Green",
    "ENCHANTED_PRISMARINE_CRYSTALS": "Enchanted Prismarine Crystals",
    #"ENCHANTED_CARROT_STICK": "Enchanted Carrot On A Stick",
    "ENCHANTED_CARROT_ON_A_STICK": "Enchanted Carrot On A Stick",
    "ENCHANTED_ENDSTONE": "Enchanted Endstone",
    "ENCHANTED_LAPIS_LAZULI_BLOCK": "Enchanted Lapis Lazuli Block",
    "ENCHANTED_COOKIE": "Enchanted Cookie",
    "ENCHANTED_STRING": "Enchanted String",
    "SLIME_BALL": "Slimeball",
    "ENDER_STONE": "End Stone",
    "ENCHANTED_RAW_FISH": "Enchanted Raw Fish",
    "ENCHANTED_ACACIA_LOG": "Enchanted Acacia Log",
    "SNOW_BALL": "Snow Ball",
    "ENCHANTED_EGG": "Enchanted Egg",
    "QUARTZ": "Quartz",
    "RAW_BEEF": "Raw Beef",
    "ENCHANTED_EYE_OF_ENDER": "Enchanted Eye Of Ender",
    "SAND": "Sand",
    "RAW_CHICKEN": "Raw Chicken",
    "MAGMA_CREAM": "Magma Cream",
    "SUGAR_CANE": "Sugar Cane",
    "ENCHANTED_LAPIS_LAZULI": "Enchanted Lapis Lazuli",
    "ENCHANTED_GHAST_TEAR": "Enchanted Ghast Tear",
    "ENCHANTED_COCOA": "Enchanted Cocoa",
    "RED_GIFT": "Red Gift",
    "ENCHANTED_RAW_BEEF": "Enchanted Raw Beef",
    "SEEDS": "Seeds",
    "ENCHANTED_LEAååR": "Enchanted Leather",
    "ENCHANTED_SPONGE": "Enchanted Sponge",
    "ENCHANTED_FEATHER": "Enchanted Feather",
    "ENCHANTED_SLIME_BLOCK": "Enchanted Slime Block",
    "ENCHANTED_OAK_LOG": "Enchanted Oak Log",
    "RABBIT_HIDE": "Rabbit Hide",
    "WHITE_GIFT": "White Gift",
    "INK_SACK": "Ink Sack",
    "FLINT": "Flint",
    "ENCHANTED_SPRUCE_LOG": "Enchanted Spruce Log",
    "WOLF_TOOTH": "Wolf Tooth",
    "ENCHANTED_ROTTEN_FLESH": "Enchanted Rotten Flesh",
    "ENCHANTED_GRILLED_PORK": "Enchanted Grilled Pork",
    "SULPHUR": "Gunpowder",
    "NETHER_STALK": "Nether Wart",
    "RABBIT": "Rabbit",
    "ENCHANTED_NETHER_STALK": "Enchanted Nether Wart",
    "ENCHANTED_REDSTONE_BLOCK": "Enchanted Redstone Block",
    "ENCHANTED_QUARTZ_BLOCK": "Enchanted Quartz Block",
    "ENCHANTED_CARROT": "Enchanted Carrot",
    "ENCHANTED_PUMPKIN": "Enchanted Pumpkin",
    "GREEN_CANDY": "Green Candy",
    "ENCHANTED_REDSTONE": "Enchanted Redstone",
    "ROTTEN_FLESH": "Rotten Flesh",
    "ENCHANTED_COOKED_FISH": "Enchanted Cooked Fish",
    "OBSIDIAN": "Obsidian",
    "ENCHANTED_MAGMA_CREAM": "Enchanted Magma Cream",
    "GRAVEL": "Gravel",
    "MELON": "Melon",
    "ENCHANTED_PACKED_ICE": "Enchanted Packed Ice",
    "RAW_FISH:3": "Pufferfish",
    "ENCHANTED_PRISMARINE_SHARD": "Enchanted Prismarine Shard",
    "ENCHANTED_IRON_BLOCK": "Enchanted Iron Block",
    "LEATHER": "Leather",
    "ENCHANTED_COOKED_MUTTON": "Enchanted Cooked Mutton",
    "BONE": "Bone",
    "RAW_FISH:1": "Salmon",
    "REVENANT_FLESH": "Revenant Flesh",
    "ENCHANTED_PORK": "Enchanted Pork",
    "ENCHANTED_GLOWSTONE": "Enchanted Glowstone",
    "ENCHANTED_RABBIT": "Enchanted Rabbit",
    "ENCHANTED_BREAD": "Enchanted Bread",
    "FEATHER": "Feather",
    "ENCHANTED_CHARCOAL": "Enchanted Charcoal",
    "ENCHANTED_BLAZE_POWDER": "Enchanted Blaze Powder",
    "NETHERRACK": "Netherrack",
    "SUMMONING_EYE": "Summoning Eye",
    "SPONGE": "Sponge",
    "BLAZE_ROD": "Blaze Rod",
    "ENCHANTED_DARK_OAK_LOG": "Enchanted Dark Oak Log",
    "SNOW_BLOCK": "Snow Block",
    "ENCHANTED_BAKED_POTATO": "Enchanted Baked Potato",
    "COMPACTOR": "Compactor",
    "ENCHANTED_DIAMOND": "Enchanted Diamond",
    "ENCHANTED_GOLD": "Enchanted Gold",
    "WISE_FRAGMENT": "Wise Dragon Fragment",
    "PROTECTOR_FRAGMENT": "Protector Dragon Fragment",
    "STRONG_FRAGMENT": "Strong Dragon Fragment",
    "YOUNG_FRAGMENT": "Young Dragon Fragment",
    "UNSTABLE_FRAGMENT": "Unstable Dragon Fragment",
    "SUPERIOR_FRAGMENT": "Superior Dragon Fragment",
    "OLD_FRAGMENT": "Old Dragon Fragment",
    "ENCHANTED_FIREWORK_ROCKET": "Enchanted Firework Rocket",
    "ENCHANTED_LAVA_BUCKET": "Enchanted Lava Bucket",
    "CATALYST": "Catalyst",
    "ENCHANTED_REDSTONE_LAMP": "Enchanted Redstone Lamp",
    "ENCHANTED_HAY_BALE": "Enchanted Hay Bale",
    "HAY_BLOCK": "Hay Bale",
    "ENCHANTED_SEEDS": "Enchanted Seeds",
    "ENCHANTED_SAND": "Enchanted Sand",
    "ENCHANTED_RED_MUSHROOM": "Enchanted Red Mushroom",
    "ENCHANTED_BROWN_MUSHROOM": "Enchanted Brown Mushroom",
    "ENCHANTED_WET_SPONGE": "Enchanted Wet Sponge",
    "HAMSTER_WHEEL": "Hamster Wheel",
    "FOUL_FLESH": "Foul Flesh",
    "RECOMBOBULATOR_3000": "Recombobulator 3000",
    "HOLY_FRAGMENT": "Holy Dragon Fragment",
    "FUMING_POTATO_BOOK": "Fuming Potato Book",
    "CARROT_BAIT": "Carrot Bait",
    "MINNOW_BAIT": "Minnow Bait",
    "FISH_BAIT": "Fish Bait",
    "LIGHT_BAIT": "Light Bait",
    "DARK_BAIT": "Dark Bait",
    "SPOOKY_BAIT": "Spooky Bait",
    "SPIKED_BAIT": "Spiked Bait",
    "BLESSED_BAIT": "Blessed Bait",
    "ICE_BAIT": "Ice Bait",
    "WHALE_BAIT": "Whale Bait",
    "ENCHANTED_CLOWNFISH": "Enchanted Clownfish",
    "RAW_FISH:2": "Clownfish",
    "ENCHANTED_BONE_BLOCK": "Enchanted Bone Block",
    "BOOSTER_COOKIE": "Booster Cookie",
    "TIGER_SHARK_TOOTH": "Tiger Shark Tooth",
    "BLUE_SHARK_TOOTH": "Blue Shark Tooth",
    "NURSE_SHARK_TOOTH": "Nurse Shark Tooth",
    "GREAT_WHITE_SHARK_TOOTH": "Great White Shark Tooth",
    "SHARK_FIN": "Shark Fin",
    "ENCHANTED_SHARK_FIN": "Enchanted Shark Fin",
    "BAZAAR_COOKIE": "Bazaar Cookie",
    "GRIFFIN_FEATHER": "Griffin Feather",
    "DAEDALUS_STICK": "Daedalus Stick",
    "ANCIENT_CLAW": "Ancient Claw",
    "ENCHANTED_ANCIENT_CLAW": "Enchanted Ancient Claw",
    "REFINED_MINERAL": "Refined Mineral",
    "SHARK_BAIT": "Shark Bait",
    "HYPER_CATALYST": "Hyper Catalyst",
    "JACOBS_TICKET": "Jacob's Ticket",
    "SPOOKY_SHARD": "Spooky Shard",
    "ECTOPLASM": "Ectoplasm",
    "JERRY_BOX_GREEN": "Green Jerry Box",
    "JERRY_BOX_BLUE": "Blue Jerry Box",
    "JERRY_BOX_PURPLE": "Purple Jerry Box",
    "JERRY_BOX_GOLDEN": "Golden Jerry Box",
    "MITHRIL_ORE": "Mithril",
    "ENCHANTED_MITHRIL": "Enchanted Mithril",
    "REFINED_MITHRIL": "Refined Mithril",
    "TITANIUM_ORE": "Titanium",
    "ENCHANTED_TITANIUM": "Enchanted Titanium",
    "REFINED_TITANIUM": "Refined Titanium",
    "STARFALL": "Starfall",
    "TREASURITE": "Treasurite",
    "DWARVEN_COMPACTOR": "Dwarven Super Compactor",
    "REFINED_DIAMOND": "Refined Diamond",
    "ROUGH_JADE_GEM": "Rough Jade Gemstone",
    "ROUGH_AMBER_GEM": "Rough Amber Gemstone",
    "ROUGH_TOPAZ_GEM": "Rough Topaz Gemstone",
    "ROUGH_SAPPHIRE_GEM": "Rough Sapphire Gemstone",
    "ROUGH_AMETHYST_GEM": "Rough Amethyst Gemstone",
    "ROUGH_JASPER_GEM": "Rough Jasper Gemstone",
    "ROUGH_RUBY_GEM": "Rough Ruby Gemstone",
    "ROUGH_OPAL_GEM": "Rough Opal Gemstone",
    "ROUGH_ONYX_GEM": "Rough Onyx Gemstone",
    "ROUGH_AQUAMARINE_GEM": "Rough Aquamarine Gemstone",
    "ROUGH_CITRINE_GEM": "Rough Citrine Gemstone",
    "ROUGH_PERIDOT_GEM": "Rough Peridot Gemstone",
    "FLAWED_JADE_GEM": "Flawed Jade Gemstone",
    "FLAWED_AMBER_GEM": "Flawed Amber Gemstone",
    "FLAWED_TOPAZ_GEM": "Flawed Topaz Gemstone",
    "FLAWED_SAPPHIRE_GEM": "Flawed Sapphire Gemstone",
    "FLAWED_AMETHYST_GEM": "Flawed Amethyst Gemstone",
    "FLAWED_JASPER_GEM": "Flawed Jasper Gemstone",
    "FLAWED_RUBY_GEM": "Flawed Ruby Gemstone",
    "FLAWED_OPAL_GEM": "Flawed Opal Gemstone",
    "FLAWED_ONYX_GEM": "Flawed Onyx Gemstone",
    "FLAWED_AQUAMARINE_GEM": "Flawed Aquamarine Gemstone",
    "FLAWED_CITRINE_GEM": "Flawed Citrine Gemstone",
    "FLAWED_PERIDOT_GEM": "Flawed Peridot Gemstone",
    "FINE_JADE_GEM": "Fine Jade Gemstone",
    "FINE_AMBER_GEM": "Fine Amber Gemstone",
    "FINE_TOPAZ_GEM": "Fine Topaz Gemstone",
    "FINE_SAPPHIRE_GEM": "Fine Sapphire Gemstone",
    "FINE_AMETHYST_GEM": "Fine Amethyst Gemstone",
    "FINE_JASPER_GEM": "Fine Jasper Gemstone",
    "FINE_RUBY_GEM": "Fine Ruby Gemstone",
    "FINE_OPAL_GEM": "Fine Opal Gemstone",
    "FINE_ONYX_GEM": "Fine Onyx Gemstone",
    "FINE_AQUAMARINE_GEM": "Fine Aquamarine Gemstone",
    "FINE_CITRINE_GEM": "Fine Citrine Gemstone",
    "FINE_PERIDOT_GEM": "Fine Peridot Gemstone",
    "FLAWLESS_JADE_GEM": "Flawless Jade Gemstone",
    "FLAWLESS_AMBER_GEM": "Flawless Amber Gemstone",
    "FLAWLESS_TOPAZ_GEM": "Flawless Topaz Gemstone",
    "FLAWLESS_SAPPHIRE_GEM": "Flawless Sapphire Gemstone",
    "FLAWLESS_AMETHYST_GEM": "Flawless Amethyst Gemstone",
    "FLAWLESS_JASPER_GEM": "Flawless Jasper Gemstone",
    "FLAWLESS_RUBY_GEM": "Flawless Ruby Gemstone",
    "FLAWLESS_OPAL_GEM": "Flawless Opal Gemstone",
    "FLAWLESS_ONYX_GEM": "Flawless Onyx Gemstone",
    "FLAWLESS_AQUAMARINE_GEM": "Flawless Aquamarine Gemstone",
    "FLAWLESS_CITRINE_GEM": "Flawless Citrine Gemstone",
    "FLAWLESS_PERIDOT_GEM": "Flawless Peridot Gemstone",
    "PERFECT_JADE_GEM": "Perfect Jade Gemstone",
    "PERFECT_AMBER_GEM": "Perfect Amber Gemstone",
    "PERFECT_TOPAZ_GEM": "Perfect Topaz Gemstone",
    "PERFECT_SAPPHIRE_GEM": "Perfect Sapphire Gemstone",
    "PERFECT_AMETHYST_GEM": "Perfect Amethyst Gemstone",
    "PERFECT_JASPER_GEM": "Perfect Jasper Gemstone",
    "PERFECT_RUBY_GEM": "Perfect Ruby Gemstone",
    "PERFECT_OPAL_GEM": "Perfect Opal Gemstone",
    "PERFECT_ONYX_GEM": "Perfect Onyx Gemstone",
    "PERFECT_AQUAMARINE_GEM": "Perfect Aquamarine Gemstone",
    "PERFECT_CITRINE_GEM": "Perfect Citrine Gemstone",
    "PERFECT_PERIDOT_GEM": "Perfect Peridot Gemstone",
    "EXP_BOTTLE": "Experience Bottle",
    "GRAND_EXP_BOTTLE": "Grand Experience Bottle",
    "TITANIC_EXP_BOTTLE": "Titanic Experience Bottle",
    "COLOSSAL_EXP_BOTTLE": "Colossal Experience Bottle",
    "MAGMA_BUCKET": "Magma Bucket",
    "PLASMA_BUCKET": "Plasma Bucket",
    "POLISHED_PUMPKIN": "Polished Pumpkin",
    "NULL_SPHERE": "Null Sphere",
    "NULL_OVOID": "Null Ovoid",
    "NULL_ATOM": "Null Atom",
    "RAW_SOULFLOW": "Raw Soulflow",
    "SOULFLOW": "Soulflow",
    "ABSOLUTE_ENDER_PEARL": "Absolute Ender Pearl",
    "TIGHTLY_TIED_HAY_BALE": "Tightly-Tied Hay Bale",
    "HARD_STONE": "Hard Stone",
    "ENCHANTED_HARD_STONE": "Enchanted Hard Stone",
    "CONCENTRATED_STONE": "Concentrated Stone",
    "PUMPKIN_GUTS": "Pumpkin Guts",
    "WEREWOLF_SKIN": "Werewolf Skin",
    "SOUL_FRAGMENT": "Soul Fragment",
    "ENCHANTED_NETHERRACK": "Enchanted Netherrack",
    "MUTANT_NETHER_STALK": "Mutant Nether Wart",
    "POWER_CRYSTAL": "Power Crystal",
    "YOGGIE": "Yoggie",
    "SLUDGE_JUICE": "Sludge Juice",
    "TIGHTLY_TIED_HAY_BALE": "Tightly Tied Hay Bale",
    "CORRUPTED_BAIT": "Corrupted Bait",
    "DARK_ORB": "Dark Orb",
    "ESSENCE_DRAGON": "Dragon Essence",
    "ESSENCE_SPIDER": "Spider Essence",
    "ESSENCE_GOLD": "Gold Essence",
    "GOBLIN_EGG_YELLOW": "Yellow Goblin Egg",
    "GOBLIN_EGG_GREEN": "Green Goblin Egg",
    "GOBLIN_EGG_RED": "Red Goblin Egg",
    "GOBLIN_EGG": "Goblin Egg",
    "GOBLIN_EGG_BLUE": "Blue Goblin Egg",
    "DUNGEON_TRAP": "Trap",
    "GIANT_FRAGMENT_LASER": "L.A.S.R.'s Eye",
    "WEAK_WOLF_CATALYST": "Weak Wolf Catalyst",
    "MINION_EXPANDER": "Minion Expander",
    "ENDER_MONOCLE": "Ender Monocle",
    "SCARF_FRAGMENT": "Scarf Fragment",
    "BONZO_FRAGMENT": "Bonzo Fragment",
    "MIMIC_FRAGMENT": "Mimic Fragment",
    "LIVID_FRAGMENT": "Livid Fragment",
    "ROCK_GEMSTONE": "Rock Gemstone",
    "BEATING_HEART": "Beating Heart",
    "RITUAL_RESIDUE": "Ritual Residue",
    "CONDENSED_FERMENTO": "Condensed Fermento",
    "END_STONE_SHULKER": "End Stone Shulker",
    "KELVIN_INVERTER": "Kelvin Inverter",
    "HAZMAT_ENDERMAN": "Hazmat Enderman",
    "LUXURIOUS_SPOOL": "Luxurious Spool",
    "NULL_EDGE": "Null Edge",
    "BEJEWELED_HANDLE": "Bejeweled Handle",
    "OPTICAL_LENS": "Optical Lens",
    "FURBALL": "Furball",
    "SOLAR_PANEL": "Solar Panel",
    "DIAMOND_ATOM": "Diamond Atom",
    "ENCHANTED_BONE_MEAL": "Enchanted Bone Meal",
    "SIMPLE_CARROT_CANDY": "Simple Carrot Candy",
    "GREAT_CARROT_CANDY": "Great Carrot Candy",
    "SUPERB_CARROT_CANDY": "Superb Carrot Candy",
    "ULTIMATE_CARROT_CANDY": "Ultimate Carrot Candy",
    "UNDEAD_CATALYST": "Undead Catalyst",
    "WITHER_CATALYST": "Wither Catalyst",
    "REVENTANT_CATALYST": "Revenant Catalyst",
    "HYPER_CATALYST": "Hyper Catalyst",
    "DUNGEON_DECOY": "Decoy",
    "DERELICT_ASHE": "Derelict Ashe",
    "FLY_SWATTER": "Fly Swatter",
    "AMBER_MATERIAL": "Amber Material",
    "HYPERGOLIC_GABAGOOL": "Hypergolic Gabagool",
    "HYPERGOLIC_IONIZED_CERAMICS": "Hypergolic Ionized Ceramics",
    "INFERNO_APEX": "Inferno Apex",
    "INFERNO_VERTEX": "Inferno Vertex",
    "OVERGROWN_GRASS": "Overgrown Grass",
    "FULL_CHUM_BUCKET": "Full Chum Bucket",
    "EMPTY_CHUM_BUCKET": "Empty Chum Bucket",
    "CHUM": "Chum",
    "GLOWY_CHUM_BAIT": "Glowy Chum Bait",
    "SOULFLOW_ENGINE": "Soulflow Engine",
    "PUMPKIN_BOMB": "Blast O' Lantern",
    "PET_ITEM_TOY_JERRY": "Jerry 3D Glasses",
    "PRECURSOR_GEAR": "Precursor Gear",
    "RED_SCARF": "Red Scarf",
    "SULPHUR_ORE": "Sulphur",
    "ENCHANTED_SULPHUR": "Enchanted Sulphur",
    "SULPHURIC_COAL": "Sulphuric Coal",
    "ROBOTRON_REFLECTOR": "Robotron Reflector",
    "CHILI_PEPPER": "Chili Pepper",
    "SIL_EX": "Silex",
    "SALT_CUBE": "Salt Cube",
    "ONYX": "Onyx",
    "OMEGA_EGG": "Omega Enchanted Egg",
    "SMALL_ENCHANTED_CHEST": "Small Storage",
    "MEDIUM_ENCHANTED_CHEST": "Medium Storage",
    "LARGE_ENCHANTED_CHEST": "Large Storage",
    "XLARGE_ENCHANTED_CHEST": "X-Large Storage",
    "XXLARGE_ENCHANTED_CHEST": "XX-Large Storage",
    "SCORCHED_POWER_CRYSTAL": "Scorched Power Crystal",
    "REHEATED_GUMMY_POLAR_BEAR": "Re-heated Gummy Polar Bear",
    "FLYCATCHER_UPGRADE": "Flycatcher",
    "IMPLOSION_SCROLL": "Implosion",
    "CROPIE": "Cropie",
    "FTX_3070": "FTX 3070",
    "PET_ITEM_VAMPIRE_FANG": "Vampire Fang",
    "ENDSTONE_GEODE": "End Stone Geode",
    "LAVA_WATER_ORB": "Lava Water Orb",
    "GIANT_FRAGMENT_BIGFOOT": "Bigfoot's Lasso",
    "MAGIC_MUSHROOM_SOUP": "Magical Mushroom Soup",
    "SUPER_MAGIC_MUSHROOM_SOUP": "Mystical Mushroom Soup",
    "LESSER_SOULFLOW_ENGINE": "Lesser Soulflow Engine",
    "LARGE_WALNUT": "Large Walnut",
    "TOIL_LOG": "Toil Log",
    "TESSELLATED_ENDER_PEARL": "Tessellated Ender Pearl",
    "AOTE_STONE": "Warped Stone",
    "INFERNO_FUEL_BLOCK": "Inferno Fuel Block",
    "PET_ITEM_EXP_SHARE_DROP": "Exp Share Core",
    "FIRST_MASTER_STAR": "First Master Star",
    "SECOND_MASTER_STAR": "Second Master Star",
    "THIRD_MASTER_STAR": "Third Master Star",
    "FOURTH_MASTER_STAR": "Fourth Master Star",
    "FIFTH_MASTER_STAR": "Fifth Master Star",
    "ENCHANTED_POPPY": "Enchanted Poppy",
    "ENCHANTED_DANDELION": "Enchanted Dandelion",
    "GOLEM_POPPY": "Ancient Rose",
    "ENTROPY_SUPPRESSOR": "Entropy Suppressor",
    "GLOWSTONE_DUST_DISTILLATE": "Glowstone Distillate",
    "MOLTEN_CUBE": "Molten Cube",
    "HEALING_TISSUE": "Healing Tissue",
    "WATER_ORB": "Water Orb",
    "GLACITE_JEWEL": "Glacite Jewel",
    "RUSTY_ANCHOR": "Rusty Anchor",
    "REFINED_AMBER": "Refined Amber",
    "BOBBIN_SCRIPTURES": "Bobbin' Scriptures",
    "CORRUPT_SOIL": "Corrupt Soil",
    "RARE_DIAMOND": "Rare Diamond",
    "THE_ART_OF_PEACE": "The Art of Peace",
    "THE_ART_OF_WAR": "The Art of War",
    "JADERALD": "Jaderald",
    "VOLTA": "Volta",
    "SUPERLITE_MOTOR": "Superlite Motor",
    "BRAIDED_GRIFFIN_FEATHER": "Braided Griffin Feather",
    "SPIRIT_WING": "Spirit Wing",
    "SPOOKY_WATER_ORB": "Spooky Water Orb",
    "SHARK_WATER_ORB": "Shark Water Orb",
    "WINTER_WATER_ORB": "Winter Water Orb",
    "SORROW": "Sorrow",
    "CRYSTAL_FRAGMENT": "Crystal Fragment",
    "DIAMONITE": "Diamonite",
    "GLOWING_MUSHROOM": "Glowing Mushroom",
    "POISONOUS_POTATO": "Poisonous Potato",
    "KISMET_FEATHER": "Kismet Feather",
    "OBSIDIAN_TABLET": "Obsidian Tablet",
    "ESSENCE_WITHER": "Wither Essence",
    "ENCHANTED_WOOL": "Enchanted Wool",
    "MITHRIL_PLATE": "Mithril Plate",
    "CHYME": "Chyme",
    "DIVAN_FRAGMENT": "Divan Fragment",
    "JERRY_STONE": "Jerry Stone",
    "MOLTEN_POWDER": "Molten Powder",
    "MAGMA_URCHIN": "Magma Urchin",
    "BAT_FIREWORK": "Bat Firework",
    "ARROW_BUNDLE_MAGMA": "Bundle of Magma Arrows",
    "BLESSED_FRUIT": "Blessed Fruit",
    "TWILIGHT_ARROW_POISON": "Twilight Arrow Poison",
    "POTATO_SPREADING": "Potato Spreading",
    "ARACHNE_KEEPER_FRAGMENT": "Arachne's Calling",
    "RED_NOSE": "Red Nose",
    "REVENANT_CATALYST": "Revenant Catalyst",
    "MAGMA_FISH": "Magmafish",
    "MAGMA_FISH_SILVER": "Silver Magmafish",
    "MAGMA_FISH_GOLD": "Gold Magmafish",
    "MAGMA_FISH_DIAMOND": "Diamond Magmafish",
    "YELLOW_FLOWER": "Dandelion",
    "ESSENCE_UNDEAD": "Undead Essence",
    "DRAGON_CLAW": "Dragon Claw",
    "LUCKY_DICE": "Lucky Dice",
    "PRECIOUS_PEARL": "Precious Pearl",
    "ENCHANTED_MYCELIUM": "Enchanted Mycelium",
    "ENCHANTED_MYCELIUM_CUBE": "Enchanted Mycelium Cube",
    "RED_ROSE": "Poppy",
    "ENCHANTED_HOPPER": "Enchanted Hopper",
    "GIANT_FRAGMENT_DIAMOND": "Diamante's Handle",
    "WITHER_BLOOD": "Wither Blood",
    "BLAZE_WAX": "Blaze Wax",
    "SUPERBOOM_TNT": "Superboom TNT",
    "SHINY_PRISM": "Shiny Prism",
    "FLOWERING_BOUQUET": "Flowering Bouquet",
    "SPIRIT_LEAP": "Spirit Leap",
    "BOOK_OF_STATS": "Book of Stats",
    "OIL_BARREL": "Oil Barrel",
    "HORNS_OF_TORMENT": "Horns of Torment",
    "FARMING_FOR_DUMMIES": "Farming for Dummies",
    "FUEL_TANK": "Fuel Tank",
    "SHADOW_WARP_SCROLL": "Shadow Warp",
    "TRANSMISSION_TUNER": "Transmission Tuner",
    "GLACIAL_FRAGMENT": "Glacial Fragment",
    "ENCHANTED_POISONOUS_POTATO": "Enchanted Poisonous Potato",
    "WOOL": "Wool",
    "SYNTHETIC_HEART": "Synthetic Heart",
    "JALAPENO_BOOK": "Jalapeno Book",
    "ICE_HUNK": "Hunk of Ice",
    "ELECTRON_TRANSMITTER": "Electron Transmitter",
    "BUDGET_HOPPER": "Budget Hopper",
    "SKYMART_BROCHURE": "Skymart Brochure",
    "STUFFED_CHILI_PEPPER": "Stuffed Chili Pepper",
    "TERRY_SNOWGLOBE": "Terry's Snowglobe",
    "CHEESE_FUEL": "Tasty Cheese",
    "KUUDRA_MANDIBLE": "Kuudra Mandible",
    "GEMSTONE_MIXTURE": "Gemstone Mixture",
    "WITHER_SHIELD_SCROLL": "Wither Shield",
    "ACACIA_BIRDHOUSE": "Acacia Birdhouse",
    "SPIDER_CATALYST": "Spider Catalyst",
    "ESSENCE_ICE": "Ice Essence",
    "MOIL_LOG": "Moil Log",
    "BLAZE_ROD_DISTILLATE": "Blaze Rod Distillate",
    "ENDERMAN_CORTEX_REWRITER": "Enderman Cortex Rewriter",
    "CRUDE_GABAGOOL_DISTILLATE": "Gabagool Distillate",
    "ENCHANTED_LEATHER": "Enchanted Leather",
    "METEOR_SHARD": "Meteor Shard",
    "MELON_BLOCK": "Melon Block",
    "NECROMANCER_BROOCH": "Necromancer's Brooch",
    "PET_ITEM_LUCKY_CLOVER_DROP": "Lucky Clover Core",
    "BURROWING_SPORES": "Burrowing Spores",
    "DEEP_SEA_ORB": "Deep Sea Orb",
    "PETRIFIED_STARFALL": "Petrified Starfall",
    "ENCHANTED_RED_SAND": "Enchanted Red Sand",
    "PITCHIN_KOI": "Pitchin' Koi",
    "GOLDEN_PLATE": "Golden Plate",
    "SADAN_BROOCH": "Sadan's Brooch",
    "CORLEONITE": "Corleonite",
    "SQUASH": "Squash",
    "DRAGON_HORN": "Dragon Horn",
    "LAPIS_CRYSTAL": "Lapis Crystal",
    "TOXIC_ARROW_POISON": "Toxic Arrow Poison",
    "BOB_OMB": "Bob-omb",
    "BLUE_ICE_HUNK": "Hunk of Blue Ice",
    "MAGMA_CREAM_DISTILLATE": "Magma Cream Distillate",
    "GIANT_TOOTH": "Giant Tooth",
    "HOT_BAIT": "Hot Bait",
    "SUBZERO_INVERTER": "Subzero Inverter",
    "NULL_BLADE": "Null Blade",
    "MITHRIL_INFUSION": "Mithril Infusion",
    "WORM_MEMBRANE": "Worm Membrane",
    "PLASMA": "Plasma",
    "ESSENCE_CRIMSON": "Crimson Essence",
    "SALMON_OPAL": "Salmon Opal",
    "ENCHANTED_COMPOST": "Compost Bundle",
    "FEL_PEARL": "Fel Pearl",
    "HORSEMAN_CANDLE": "Horseman's Candle",
    "SOUL_STRING": "Soul String",
    "FROZEN_BAUBLE": "Frozen Bauble",
    "GOLDEN_BALL": "Golden Ball",
    "GIANT_FRAGMENT_BOULDER": "Jolly Pink Rock",
    "MANDRAA": "Mandraa",
    "RADIOACTIVE_VIAL": "Radioactive Vial",
    "BULKY_STONE": "Bulky Stone",
    "GREAT_WHITE_TOOTH_MEAL": "Great White Tooth Meal",
    "CONTROL_SWITCH": "Control Switch",
    "DIAMOND_SPREADING": "Diamond Spreading",
    "NETHER_STALK_DISTILLATE": "Nether Wart Distillate",
    "ESSENCE_DIAMOND": "Diamond Essence",
    "ENCHANTED_SULPHUR_CUBE": "Enchanted Sulphur Cube",
    "CRUDE_GABAGOOL": "Crude Gabagool",
    "DRAGON_SCALE": "Dragon Scale",
    "MYCEL": "Mycelium",
    "WHIPPED_MAGMA_CREAM": "Whipped Magma Cream",
    "HARDENED_WOOD": "Hardened Wood",
    "HEAVY_GABAGOOL": "Heavy Gabagool",
    "AUTO_SMELTER": "Auto Smelter",
    "ECCENTRIC_PAINTING": "Eccentric Painting",
    "REAPER_PEPPER": "Reaper Pepper",
    "SPIRIT_DECOY": "Spirit Stone",
    "PURE_MITHRIL": "Pure Mithril",
    "PET_ITEM_TIER_BOOST_DROP": "Tier Boost Core",
    "ROCK_CANDY": "Rock Candy",
    "SEARING_STONE": "Searing Stone",
    "MIDAS_JEWEL": "Midas Jewel",
    "VITAMIN_DEATH": "Vitamin Death",
    "BOX_OF_SEEDS": "Box of Seeds",
    "HOT_STUFF": "Hot Stuff",
    "FERMENTO": "Fermento",
    "CANDY_CORN": "Candy Corn",
    "ENCHANTED_RED_SAND_CUBE": "Enchanted Red Sand Cube",
    "INFLATABLE_JERRY": "Inflatable Jerry",
    "FUEL_GABAGOOL": "Fuel Gabagool",
    "DRILL_ENGINE": "Drill Engine",
    "COMPOST": "Compost",
    "DIRT_BOTTLE": "Dirt Bottle",
    "SPIRIT_BONE": "Spirit Bone",
    "MITE_GEL": "Mite Gel",
    "MIXED_MITE_GEL": "Mixed Mite Gel",
    "DUNGEON_CHEST_KEY": "Dungeon Chest Key",
    "GOLDEN_POWDER": "Golden Powder",
    "JUNGLE_KEY": "Jungle Key",
    "PREMIUM_FLESH": "Premium Flesh",
    "SUSPICIOUS_VIAL": "Suspicious Vial",
    "WOOD_SINGULARITY": "Wood Singularity",
    "SCORCHED_BOOKS": "Scorched Books",
    "SAND:1": "Red Sand",
    "DIVER_FRAGMENT": "Emperor's Skull",
    "WISHING_COMPASS": "Wishing Compass",
    "ASCENSION_ROPE": "Ascension Rope",
    "BUBBA_BLISTER": "Bubba Blister",
    "DISPLACED_LEECH": "Displaced Leech",
    "LUSH_BERBERIS": "Lush Berberis",
    "ENCHANTED_LUSH_BERBERIS": "Enchanted Lush Berberis",
    "BERBERIS_FUEL_INJECTOR": "Berberis Fuel Injector",
    "THORN_FRAGMENT": "Thorn Fragment",
    "HEMOVIBE": "Hemovibe",
    "HEMOGLASS": "Hemoglass",
    "HEMOBOMB": "Hemobomb",
    "CHOCOLATE_CHIP": "Fang-tastic Chocolate Chip",
    "VERY_CRUDE_GABAGOOL": "Very Crude Gabagool",
    "EXPORTABLE_CARROTS": "Exportable Carrots",
    "METAPHYSICAL_SERUM": "Metaphysical Serum",
    "PRESUMED_GALLON_OF_RED_PAINT": "Presumed Gallon of Red Paint",
    "AGARIMOO_TONGUE": "Agarimoo Tongue",
    "FULL_JAW_FANGING_KIT": "Full-Jaw Fanging Kit",
    "AMALGAMATED_CRIMSONITE_NEW": "Amalgamated Crimsonite",
    "CAPSAICIN_EYEDROPS_NO_CHARGES": "Capsaicin Eyedrops",
    "FRESHLY_MINTED_COINS": "Freshly-Minted Coins",
    "PARTY_GIFT": "Party Gift",
    "BEADY_EYES": "Beady Eyes",
    "HORN_OF_TAURUS": "Horn of Taurus",
    "X": "X",
    "Y": "Y",
    "Z": "Z",
    "OLD_LEATHER_BOOT": "Old Leather Boot",
    "ARCHITECT_FIRST_DRAFT": "Architect's First Draft",
    "FLAMES": "Flames",
    "MAGMAG": "Magmag",
    "MAGMA_LORD_FRAGMENT": "Magma Lord Fragment",
    "TUNGSTEN": "Tungsten",
    "ENCHANTED_TUNGSTEN": "Enchanted Tungsten",
    "REFINED_TUNGSTEN": "Refined Tungsten",
    "TUNGSTEN_PLATE": "Tungsten Plate",
    "TUNGSTEN_KEY": "Tungsten Key",
    "UMBER": "Umber",
    "ENCHANTED_UMBER": "Enchanted Umber",
    "REFINED_UMBER": "Refined Umber",
    "UMBER_PLATE": "Umber Plate",
    "UMBER_KEY": "Umber Key",
    "PERFECT_PLATE": "Perfect Plate",
    "WINTER_FRAGMENT": "Winter Fragment",
    "PET_CAKE": "Pet Cake",
    "HONEY_JAR": "Honey Jar",
    "THUNDER_SHARDS": "Thunder Shards",
    "ENCHANTED_WHEAT": "Enchanted Wheat",
    "CUP_OF_BLOOD": "Cup Of Blood",
    "BROKEN_RADAR": "Broken Radar",
    "GLOSSY_GEMSTONE": "Glossy Gemstone",
    "SPOTLITE": "Spotlite",
    "SPECTRE_DUST": "Spectre Dust",
    "BLAZEN_SPHERE": "Blazen Sphere",
    "BLOOD_SOAKED_COINS": "Blood-Soaked Coins",
    "MUTATED_BLAZE_ASHES": "Mutated Blaze Ashes",
    "SUSPICIOUS_SCRAP": "Suspicious Scrap",
    "DUNG": "Dung",
    "GLEAMING_CRYSTAL": "Gleaming Crystal",
    "RUSTY_COIN": "Rusty Coin",
    "GUARDIAN_LUCKY_BLOCK": "Guardian Lucky Block",
    "BRIMSTONE_HANDLE": "Brimstone Handle",
    "HALF_EATEN_MUSHROOM": "Half-Eaten Mushroom",
    "LUMP_OF_MAGMA": "Lump of Magma",
    "COMPACT_OOZE": "Compact Ooze",
    "MILLENIA_OLD_BLAZE_ASHES": "Millennia-Old Blaze Ashes",
    "EXPIRED_PUMPKIN": "Expired Pumpkin",
    "TROUBLED_BUBBLE": "Troubled Bubble",
    "DIGESTED_MUSHROOMS": "Digested Mushrooms",
    "FROZEN_BAIT": "Frozen Bait",
    "JUNGLE_HEART": "Jungle Heart",
    "PET_ITEM_CHOCOLATE_SYRINGE": "Chocolate Syringe",
    "VOLCANIC_ROCK": "Volcanic Rock",
    "FINE_FLOUR": "Fine Flour",
    "SKELETON_KEY": "Skeleton Key",
    "BOUNCY_BEACH_BALL": "Bouncy Beach Ball",
    "CORRUPTED_FRAGMENT": "Corrupted Fragment",
    "BEZOS": "Bezos",
    "KUUDRA_TEETH": "Kuudra Teeth",
    "FAKE_SHURIKEN": "Extremely Real Shuriken",
    "PET_ITEM_PURE_MITHRIL_GEM": "Pure Mithril Gem",
    "SLEEPY_HOLLOW": "Sleepy Hollow",
    "LAVA_SHELL": "Lava Shell",
    "BLAZE_ASHES": "Blaze Ashes",
    "TORN_CLOTH": "Torn Cloth",
    "BLUE_RING": "Blue Ring",
    "MAGMA_CHUNK": "Magma Chunk",
    "TREASURE_BAIT": "Treasure Bait",
    "WORM_BAIT": "Worm Bait",
    "GOLDEN_FRAGMENT": "Golden Fragment",
    "HEAVY_PEARL": "Heavy Pearl",
    "SINGED_POWDER": "Singed Powder",
    "CLIPPED_WINGS": "Clipped Wings",
    "FREE_WILL": "Free Will",
    "BUSTED_BELT_BUCKLE": "Busted Belt Buckle",
    "FRIGID_HUSK": "Frigid Husk",
    "HIGHLITE": "Highlite",
    "BURNING_EYE": "Burning Eye",
    "WITHER_SOUL": "Wither Soul",
    "GLACITE": "Glacite",
    "ENCHANTED_GLACITE": "Enchanted Glacite",
    "GLACITE_AMALGAMATION": "Glacite Amalgamation",
    "FLAMING_HEART": "Flaming Heart",
    "FRIED_FEATHER": "Fried Feather",
    "LEATHER_CLOTH": "Leather Cloth",
    "GIANT_BOUNCY_BEACH_BALL": "Giant Bouncy Beach Ball",
    "REKINDLED_EMBER_FRAGMENT": "Rekindled Ember Fragment",
    "PLANT_MATTER": "Plant Matter",
    "MAGMA_CORE": "Magma Core",
    "HOTSPOT_BAIT": "Hotspot Bait",
    "GOLDEN_BAIT": "Golden Bait",
    "DARK_CANDY": "Dark Candy",
    "KADA_LEAD": "Kada Lead",
    "BLOOD_STAINED_COINS": "Blood-Stained Coins",
    "TENTACLE_MEAT": "Tentacle Meat",
    "ARACHNE_FANG": "Arachne's Fang",
    "GAZING_PEARL": "Gazing Pearl",
    "CORRUPTED_NETHER_STAR": "Nether Star",
    "ORB_OF_ENERGY": "Orb of Energy",
    "SQUEAKY_TOY": "Squeaky Toy",
    "MATCH_STICKS": "Match-Sticks",
    "TITANIUM_TESSERACT": "Titanium Tesseract",
    "CHAIN_END_TIMES": "Chain of End Times",
    "TITANOBOA_SHED": "Titanoboa Shed",
    "GLACITE_SHARD": "Glacite Shard",
    "LUMINO_FIBER": "Lumino Fiber",
    "HALLOWED_SKULL": "Hallowed Skull",
    "BRONZE_BOWL": "Bronze Bowl",
    "GOLDEN_BOUNTY": "Golden Bounty",
    "ALLIGATOR_SKIN": "Alligator Skin",
    "POCKET_ICEBERG": "Pocket Iceberg",
    "PRECURSOR_APPARATUS": "Precursor Apparatus",
    "MAGIC_TOP_HAT": "Magic Top Hat",
    "ENCHANTED_CLAY_BLOCK": "Enchanted Clay Block",
    "CALCIFIED_HEART": "Calcified Heart",
    "POISON_SAMPLE": "Poison Sample",
    "SPELL_POWDER": "Spell Powder",
    "BAYOU_WATER_ORB": "Bayou Water Orb",
    "PYROCLASTIC_SCALE": "Pyroclastic Scale",
    "SCUTTLER_SHELL": "Scuttler Shell",
    "OCTOPUS_TENDRIL": "Octopus Tendril",
    "BLACK_WOOLEN_YARN": "Black Woolen Yarn",
    "MOOGMA_PELT": "Moogma Pelt",
    "CAN_OF_WORMS": "Can of Worms",
    "HOTSPOT_WATER_ORB": "Hotspot Water Orb",
    "DWARVEN_OS_ORE_OATS": "Dwarven O's Ore Oats",
    "DWARVEN_OS_GEMSTONE_GRAHAMS": "Dwarven O's Gemstone Grahams",
    "DWARVEN_OS_BLOCK_BRAN": "Dwarven O's Block Bran",
    "DWARVEN_TREASURE": "Dwarven Treasure",
    "DWARVEN_OS_METALLIC_MINIS": "Dwarven O's Metallic Minis",
    "WRIGGLING_LARVA": "Wriggling Larva",
    "REFINED_BOTTLE_OF_JYRRE": "Refined Bottle of Jyrre",
    "SCORCHED_CRAB_STICK": "Scorched Crab Stick",
    "DIVAN_POWDER_COATING": "Divan's Powder Coating",
    "REFINED_DARK_CACAO_TRUFFLE": "Refined Dark Cacao Truffle",
    "POLARVOID_BOOK": "Polarvoid Book",
    "AVARICIOUS_CHALICE": "Avaricious Chalice",
    "SUPREME_CHOCOLATE_BAR": "Supreme Chocolate Bar",
    "SEVERED_PINCER": "Severed Pincer",
    "GOLD_BOTTLE_CAP": "Gold Bottle Cap",
    "MANA_DISINTEGRATOR": "Mana Disintegrator",
    "OVERFLOWING_TRASH_CAN": "Overflowing Trash Can",
    "ARACHNE_FRAGMENT": "Arachne Fragment",
    "GENERATOR_UPGRADE_STONE_CLAY_12": "Clay Minion XII Upgrade Stone",
    "GENERATOR_UPGRADE_STONE_FISHING_12": "Fishing Minion XII Upgrade Stone",
    "DARK_QUEENS_SOUL_DROP": "Dark Queen's Soul",
    "BOOKWORM_BOOK": "Bookworm's Favorite Book",
    "MOBY_DUCK_COLLECTOR_EDITION": "Moby-Duck: Collector's Edition",
}

items = list(raw_items.values())

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/search')
def search():
    query = request.args.get('q', '').lower()
    results = [item for item in items if query in item.lower()]
    return jsonify(results[:5])  # Limit to top 5 matches

@app.route('/moneyMethods')
def money_methods():
    return render_template('moneyMethods.html')

@app.route('/testingStuff')
def testing_stuff():
    return render_template('testingStuff.html')

@app.route('/statsCalculator')
def stats_calculator():
    return render_template('statsCalculator.html')

if __name__ == '__main__':
    app.run(debug=True)


input("Press Enter to exit...")  # Keep the script running until Enter is pressed